### ISSUE TITLE
`build-external` is failing

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/developer.chrome.com#5334]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/12857772/219446414-8fcb69f8-7603-47a9-af52-9227845e5795.png">

**Comment by devnook** [comment]
Works in TS 4.4.4, but breaks in TS 4.7.1+ Full error for further debugging:

Error: failed to parse typedoc: node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.

Looks like there was additional methor added to AbortSignal (abort(reason?: any)).

**Comment by devnook** [comment]
Related: https://github.com/GoogleChrome/workbox/issues/3179
